apiVersion: v1
kind: ReplicationController
metadata:
  name: catalog
spec:
  replicas: 1
  selector:
    name: catalog
  template:
    metadata:
      labels:
        name: catalog
        role: frontend
        app: catalog
      name: catalog
    spec:
      containers:
        - name: catalog
          image: zutherb/catalog-frontend
          ports:
            - containerPort: 80
          env:
            - name: CHECKOUT_DESIGN
              value: "standard"
---
kind: Service
apiVersion: v1
metadata:
  labels:
      name: catalog
      role: backend
  name: catalog
spec:
  type: NodePort
  ports:
    - name: catalog
      port: 7777
      targetPort: 80
  selector:
      app: catalog
