apiVersion: v1
kind: Service
metadata:
  name: two-containers
  labels:
    app: two-containers
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: nginx-http-port
  selector:
    app: two-containers
---
apiVersion: v1
kind: Pod
metadata:
  name: two-containers
  labels:
    app: two-containers
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: 1st
    image: nginx
    ports:
    - name: nginx-http-port
      containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: 2nd
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          echo "$(date) <br>" >> /html/index.html;
          sleep 2;
        done
