apiVersion: v1
kind: Pod
metadata:
  name: access-secret-via-env
spec:
  containers:
    - name: consuming-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: DB_HOST
          value: someDBServiceName
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password
  restartPolicy: Never