kind: Service
apiVersion: v1
metadata:
  name: r-shiny
  labels:
    app: r-shiny
spec:
  type: NodePort
  ports:
  - port: 3838
    targetPort: 3838
    protocol: TCP
    name: web
  selector:
    app: r-shiny